version: '3.9'

services:

  db:
    image: postgres:12
    container_name: "HFTApp"
    env_file: 
      - database.env
    ports: 
      - "5432:5432"
    volumes: 
      - db-data:/var/lib/postgresql/data
  
  server:
    build: 
      context: .
      dockerfile: DockerFile
    depends_on:
      - db
    ports:
      - "5000:5000"
  
volumes: 
  db-data: